<a href="https://colab.research.google.com/github/ihagoSantos/machine_learning/blob/main/neural_network_sonar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes Neurais Artificiais


Ilustra o funcionamento do algoritmo de redes neurais.

Este notebook foi desenvolvido para o ambiente GOOGLE COLAB ([colab.research.google.com](https://colab.research.google.com)).

Prof. Hugo de Paula

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

np.set_printoptions(precision=2)

# Carregamento da base

In [5]:
from google.colab import files
uploaded = files.upload()

Saving sonar.xlsx to sonar.xlsx


In [7]:
sonar = pd.read_excel('sonar.xlsx', sheet_name=0)

# Transformação de dados

In [8]:
X = sonar.iloc[:, 0: (sonar.shape[1] - 1)]
X

Atributo_1  Atributo_2  Atributo_3  Atributo_4  Atributo_5  Atributo_6  \
0        0.0200      0.0371      0.0428      0.0207      0.0954      0.0986   
1        0.0453      0.0523      0.0843      0.0689      0.1183      0.2583   
2        0.0262      0.0582      0.1099      0.1083      0.0974      0.2280   
3        0.0100      0.0171      0.0623      0.0205      0.0205      0.0368   
4        0.0762      0.0666      0.0481      0.0394      0.0590      0.0649   
..          ...         ...         ...         ...         ...         ...   
203      0.0187      0.0346      0.0168      0.0177      0.0393      0.1630   
204      0.0323      0.0101      0.0298      0.0564      0.0760      0.0958   
205      0.0522      0.0437      0.0180      0.0292      0.0351      0.1171   
206      0.0303      0.0353      0.0490      0.0608      0.0167      0.1354   
207      0.0260      0.0363      0.0136      0.0272      0.0214      0.0338   

     Atributo_7  Atributo_8  Atributo_9  Atributo_10  ...  Atributo_51  \
0        0.1539      0.1601      0.3109       0.2111  ...       0.0232   
1        0.2156      0.3481      0.3337       0.2872  ...       0.0125   
2        0.2431      0.3771      0.5598       0.6194  ...       0.0033   
3        0.1098      0.1276      0.0598       0.1264  ...       0.0241   
4        0.1209      0.2467      0.3564       0.4459  ...       0.0156   
..          ...         ...         ...          ...  ...          ...   
203      0.2028      0.1694      0.2328       0.2684  ...       0.0203   
204      0.0990      0.1018      0.1030       0.2154  ...       0.0051   
205      0.1257      0.1178      0.1258       0.2529  ...       0.0155   
206      0.1465      0.1123      0.1945       0.2354  ...       0.0042   
207      0.0655      0.1400      0.1843       0.2354  ...       0.0181   

     Atributo_52  Atributo_53  Atributo_54  Atributo_55  Atributo_56  \
0         0.0027       0.0065       0.0159       0.0072       0.0167   
1         0.0084       0.0089       0.0048       0.0094       0.0191   
2         0.0232       0.0166       0.0095       0.0180       0.0244   
3         0.0121       0.0036       0.0150       0.0085       0.0073   
4         0.0031       0.0054       0.0105       0.0110       0.0015   
..           ...          ...          ...          ...          ...   
203       0.0116       0.0098       0.0199       0.0033       0.0101   
204       0.0061       0.0093       0.0135       0.0063       0.0063   
205       0.0160       0.0029       0.0051       0.0062       0.0089   
206       0.0086       0.0046       0.0126       0.0036       0.0035   
207       0.0146       0.0129       0.0047       0.0039       0.0061   

     Atributo_57  Atributo_58  Atributo_59  Atributo_60  
0         0.0180       0.0084       0.0090       0.0032  
1         0.0140       0.0049       0.0052       0.0044  
2         0.0316       0.0164       0.0095       0.0078  
3         0.0050       0.0044       0.0040       0.0117  
4         0.0072       0.0048       0.0107       0.0094  
..           ...          ...          ...          ...  
203       0.0065       0.0115       0.0193       0.0157  
204       0.0034       0.0032       0.0062       0.0067  
205       0.0140       0.0138       0.0077       0.0031  
206       0.0034       0.0079       0.0036       0.0048  
207       0.0040       0.0036       0.0061       0.0115  

[208 rows x 60 columns]

In [9]:
le = LabelEncoder()
y = le.fit_transform(sonar.iloc[:,(sonar.shape[1] - 1)])
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
class_names = le.classes_
class_names

array(['Mina', 'Rocha'], dtype=object)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

# MLP com uma camada oculta
O bloco a seguir testa a rede neural com um camada oculta com 100 neurônios.

São totalizados 6.100 pesos diferentes que precisarão ser ajustados na fase de treinamento.

O parâmetro solver='lbfgs' foi escolhido por ser mais adequado para treinamento com bases pequenas (menores que alguns milhares de registros).

solver : {'lbfgs', 'sgd', 'adam'}, default='adam'
    The solver for weight optimization.

'lbfgs' is an optimizer in the family of quasi-Newton methods.

'sgd' refers to stochastic gradient descent.

'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba

    Note: The default solver 'adam' works pretty well on relatively large datasets (with thousands of training samples or more) in terms of both training time and validation score. For small datasets, however, 'lbfgs' can converge faster and perform better.


In [24]:
def sumary(classifier, X_train, y_train, X_test, y_test, y_pred):
  print("-"*100)
  print("Camadas da rede: {}".format(classifier.n_layers_))
  print("Neurônios na camada oculta: {}".format(classifier.hidden_layer_sizes))
  print("Neurônios na camada de saída: {}".format(classifier.n_outputs_))
  print("Pesos na camada de entrada: {}".format(classifier.coefs_[0].shape))
  print("Pesos na camada oculta: {}".format(classifier.coefs_[1].shape))
  print("-"*100)
  print("Acurácia na base de treinamento: {:.2f}".format(classifier.score(X_train, y_train)))
  print("Acurácia na base de teste: {:.2f}".format(classifier.score(X_test, y_test)))
  print("-"*100)
  print(classification_report(y_test, y_pred, target_names=class_names))
  print("-"*100)

  #calcula matriz de confusão
  print("Matriz de confusão: \n",confusion_matrix(y_test, y_pred))
  print("-"*100)

In [25]:
# Rede Perceptron Multicamadas (MLP): Configuração default otimizando a função log-loss
# Uma camada oculta com 100 neurônios.
mlp = MLPClassifier(solver='lbfgs', random_state=0)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

In [26]:
sumary(
    classifier=mlp,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    y_pred=y_pred
)


----------------------------------------------------------------------------------------------------
Camadas da rede: 3
Neurônios na camada oculta: (100,)
Neurônios na camada de saída: 1
Pesos na camada de entrada: (60, 100)
Pesos na camada oculta: (100, 1)
----------------------------------------------------------------------------------------------------
Acurácia na base de treinamento: 1.00
Acurácia na base de teste: 0.86
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

        Mina       0.78      0.88      0.82         8
       Rocha       0.92      0.85      0.88        13

    accuracy                           0.86        21
   macro avg       0.85      0.86      0.85        21
weighted avg       0.86      0.86      0.86        21

----------------------------------------------------------------------------------------------------
Matriz de confusão: 
 [[ 7  1]
 [ 2 11]]
-

### MLP com duas camadas ocultas

O bloco a seguir testa a rede neural com duas camadas ocultas.

A primeira camada possui 100 neurônios, enquanto a segunda camada possui 60 neurônios.

São totalizados 12.100 pesos diferentes que precisarão ser ajustados na fase de treinamento.

Com essa rede será possível observar que aumentar arbitrariamente a dimensão da sua rede neural não garante um aumento arbitrário da performance do modelo.

In [29]:
mlp_2 = MLPClassifier(
    solver='lbfgs',
    hidden_layer_sizes=[100, 60],
    random_state=0
)

mlp_2.fit(X_train, y_train)
y_pred_2 = mlp.predict(X_test)

In [30]:
sumary(
    classifier=mlp_2,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    y_pred=y_pred_2
)

----------------------------------------------------------------------------------------------------
Camadas da rede: 4
Neurônios na camada oculta: [100, 60]
Neurônios na camada de saída: 1
Pesos na camada de entrada: (60, 100)
Pesos na camada oculta: (100, 60)
----------------------------------------------------------------------------------------------------
Acurácia na base de treinamento: 1.00
Acurácia na base de teste: 0.86
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

        Mina       0.78      0.88      0.82         8
       Rocha       0.92      0.85      0.88        13

    accuracy                           0.86        21
   macro avg       0.85      0.86      0.85        21
weighted avg       0.86      0.86      0.86        21

----------------------------------------------------------------------------------------------------
Matriz de confusão: 
 [[ 7  1]
 [ 2 11

### *Overfitting* por excesso de neurônios

A forma mais eficiente para se determinar o número de neurônios na camada oculta é por *busca sistemática*.

Um artigo interessante que ilustra diversas heurísticas para resolver o problema pode ser visto em:

D. Stathakis (2009) *How many hidden layers and nodes?*, **International Journal of Remote Sensing**, 30:8, 2133-2147, DOI: 10.1080/01431160802549278


 Entretanto, um ponto de partida inicial muito utilizado corresponde ao:

 *(num_entradas + num_saídas) / 2.*

 Note que a rede manteve a mesma performance das topologias anteriores.

In [32]:
mlp_3 = MLPClassifier(solver='lbfgs', random_state=0, hidden_layer_sizes=[31])
mlp_3.fit(X_train, y_train)
y_pred_3 = mlp_3.predict(X_test)

In [33]:
sumary(
    classifier=mlp_3,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    y_pred=y_pred_3
)

----------------------------------------------------------------------------------------------------
Camadas da rede: 3
Neurônios na camada oculta: [31]
Neurônios na camada de saída: 1
Pesos na camada de entrada: (60, 31)
Pesos na camada oculta: (31, 1)
----------------------------------------------------------------------------------------------------
Acurácia na base de treinamento: 1.00
Acurácia na base de teste: 0.86
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

        Mina       0.73      1.00      0.84         8
       Rocha       1.00      0.77      0.87        13

    accuracy                           0.86        21
   macro avg       0.86      0.88      0.86        21
weighted avg       0.90      0.86      0.86        21

----------------------------------------------------------------------------------------------------
Matriz de confusão: 
 [[ 8  0]
 [ 3 10]]
-----

### Ajustamento dos dados

As redes neurais a seguir irão testar a hipótese de que uma MLP é robusta quanto a dados não normalizados.

Os dados serão padronizados pelo Z-score.

A normalização dos dados não irá acarretar em nenhume melhoria da rede.

In [34]:
# Calcula a média e o desvio padrão de cada atributo de treinamento
mean_on_train = X_train.mean(axis=0)
std_on_train = X_train.std(axis=0)
print("Média: {}".format(mean_on_train))
print("Desvio Padrão: {}".format(mean_on_train))

Média: Atributo_1     0.029979
Atributo_2     0.039767
Atributo_3     0.046020
Atributo_4     0.055112
Atributo_5     0.076148
Atributo_6     0.104155
Atributo_7     0.121490
Atributo_8     0.135779
Atributo_9     0.181544
Atributo_10    0.210220
Atributo_11    0.238129
Atributo_12    0.251933
Atributo_13    0.272655
Atributo_14    0.294108
Atributo_15    0.315584
Atributo_16    0.372068
Atributo_17    0.407910
Atributo_18    0.443486
Atributo_19    0.502684
Atributo_20    0.567097
Atributo_21    0.612487
Atributo_22    0.621827
Atributo_23    0.642072
Atributo_24    0.671447
Atributo_25    0.675375
Atributo_26    0.699522
Atributo_27    0.698603
Atributo_28    0.690112
Atributo_29    0.637016
Atributo_30    0.579259
Atributo_31    0.502161
Atributo_32    0.438272
Atributo_33    0.418029
Atributo_34    0.405779
Atributo_35    0.392505
Atributo_36    0.380615
Atributo_37    0.362989
Atributo_38    0.341971
Atributo_39    0.330142
Atributo_40    0.313574
Atributo_41    0.292567
Atributo_

In [37]:
# Normaliza os atributos de entrada pela norma Z = (X - média) / desvio padrão
# afterwards, mean=0, std=1
X_train_scaled = (X_train - mean_on_train) / std_on_train
# usa a mesma transformação na base de teste
X_test_scaled = (X_test - mean_on_train)/ std_on_train
print("X Train Scaled: \n{}".format(X_train_scaled))
print("X Test Scaled: \n{}".format(X_test_scalled))

X Train Scaled: 
     Atributo_1  Atributo_2  Atributo_3  Atributo_4  Atributo_5  Atributo_6  \
15    -0.007495    0.638671    0.483103    0.762932    1.483681    2.098394   
7      0.919905    0.441774    0.971801   -0.478792    0.689278   -0.200289   
55    -0.414544   -0.827774   -0.858270   -0.631429   -0.372824   -1.396543   
92    -0.166958   -0.604427   -0.524836   -1.010960   -0.711792   -0.570558   
134    3.286664    1.975810   -0.517200    0.589669   -0.023425    0.139822   
..          ...         ...         ...         ...         ...         ...   
67     0.286252    0.015652   -0.364482   -0.532421    0.101732    0.503389   
192   -1.023019   -0.384020   -0.608830    0.020373    0.303375    0.175006   
117   -0.301242   -0.857161   -0.840453    0.599982    0.618008    0.778159   
47     0.307233   -0.342877   -0.580832   -0.672683   -1.012518   -0.516945   
172   -0.502668    0.136142    0.040221    0.302958    1.483681   -0.258929   

     Atributo_7  Atributo_8  Atrib

In [38]:
# A rede atinge o número máximo de iterações, mas não converge
mlp_4 = MLPClassifier(solver='lbfgs', hidden_layer_sizes=[31], random_state=0)
mlp_4.fit(X_train_scaled, y_train)
print("Acurácia da base de treinamento: {:.2f}".format(mlp_4.score(X_train_scaled, y_train)))
print("Acurácia da base de teste: {:.2f}".format(mlp_4.score(X_test_scaled, y_test)))

Acurácia da base de treinamento: 1.00
Acurácia da base de teste: 0.86


In [39]:
# Aumentando o número máximo de iterações
mlp_5 = MLPClassifier(solver='lbfgs', hidden_layer_sizes=[31], max_iter=1000, random_state=0)
mlp_5.fit(X_train_scaled, y_train)
print("Acurácia da base de treinamento: {:.2f}".format(mlp_5.score(X_train_scaled, y_train)))
print("Acurácia da base de teste: {:.2f}".format(mlp_5.score(X_test_scaled, y_test)))

Acurácia da base de treinamento: 1.00
Acurácia da base de teste: 0.86
